export { SectionEyebrow } from "./section-eyebrow";
export { SoftwareProductsCarousel } from "./software-products-carousel";
export { ProductShowcase } from "./product-showcase";
export type { ProductShowcaseProps, ProdutoData } from "./product-showcase";
export { ProdutosAccordionSection } from "./produtos-accordion-section";
export type { ProdutosAccordionSectionProps } from "./produtos-accordion-section";
export { GenericInfoSection } from "./generic-info-section";
export type { GenericInfoSectionProps } from "./generic-info-section";
export { WebsitePortfolioCarousel } from "./website-portfolio-carousel";
export { TrustedLogosMarquee } from "./trusted-logos-marquee";
export { SmartIntegrationsTabs } from "./smart-integrations-tabs";
export { BaseInternalHero } from "./base-internal-hero";
export type { BaseInternalHeroProps, HeroSlide } from "./base-internal-hero";
export { GradientHero } from "./gradient-hero";
export type { GradientHeroProps, GradientHeroSlide, GradientHeroBadge } from "./gradient-hero";
export { CertificacoesSection } from "./certificacoes-section";
export type { CertificacoesSectionProps } from "./certificacoes-section";
export { WallOfLoveSection } from "./wall-of-love-section";
